### ISSUE TITLE
BMI as required variable

### ISSUE THREAD

**Issue by mglev1n** [bcjaeger/PooledCohort#2]
From my understanding, in the new PREVENT equations BMI is only required for estimating heart failure risk, and is not considered in the 10- or 30-year ASCVD prediction models. This seems consistent with the current PREVENT covariates data, where the BMI coefficients are 0 for all models except the heart failure models. However, even though the BMI variable is not mandatory for estimating ASCVD risk, if running the `PooledCohort::predict_10yr_ascvd_risk()` function on a dataset that is missing a bmi variable, the following error occurs:
```
Caused by error in `._predict_risk()`:
! missing required variables for PREVENT equations: bmi
```

This error can currently be overridden by adding a dummy `bmi` variable to the dataset. It may be worth considering more specific argument/variable validation that considers both `pred_type` and `equation_version`, rather than at the overall `equation_version` / model level alone (eg. PCE, PREVENT, etc.): https://github.com/bcjaeger/PooledCohort/blob/63d03e4e59173db2ce3cddfacc99bcedeb8af7f2/R/predict_risk.R#L910-L928

**Comment by bcjaeger** [comment]
Thank you! That is a very good suggestion. I will make an update to prevent the unnecessary errors from BMI
